"""Add new_test_scope to AIStrategy

Revision ID: 5996ba926bed
Revises: 328fdb59fc00
Create Date: 2026-07-19 17:03:20.990877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5996ba926bed'
down_revision: Union[str, Sequence[str], None] = '328fdb59fc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_strategies', sa.Column('new_test_scope', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_strategies', 'new_test_scope')
    # ### end Alembic commands ###
