"""add tech_details

Revision ID: 8dc6ec6fc22f
Revises: 5996ba926bed
Create Date: 2026-07-20 11:43:46.948677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc6ec6fc22f'
down_revision: Union[str, Sequence[str], None] = '5996ba926bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('tech_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'tech_details')
    # ### end Alembic commands ###
